services:
  - type: web
    name: notes-backend
    env: java
    plan: free
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/notes-management-system-0.0.1-SNAPSHOT.jar
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    buildFilter:
      paths:
        - "pom.xml"
        - "src/**"
        - "target/**"
