services:
  - type: web
    name: notes-backend
    runtime: docker
    plan: free
    dockerfilePath: Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_OPTS
        value: -Xmx512m -Xms256m
    buildFilter:
      paths:
        - "Dockerfile"
        - "pom.xml"
        - "src/**"
